### ISSUE TITLE
The sort A-Z functionality is not working on the file submission page

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#1024]
Nothing happens when selected

**Comment by KarenPorter** [comment]
could get rid of the functionality.

**Comment by KarenPorter** [comment]
Fixed on staging / staging.  Ready to test

**Comment by aekhendry** [comment]
Better but still not right. It clearly makes an attempt to sort, but it is not doing so correctly

**Comment by aekhendry** [comment]
Moving to backlog as not urgent
