### ISSUE TITLE
Add compound file - select a SMILES column, then change back to 'no structure' - process file button

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#240]
Add compound file - select a SMILES column, then change back to 'no structure' - process file button remains greyed out.

**Comment by PaulBarrett79** [comment]
Not only does the process file grey out, you get a warning saying the file is invalid

**Comment by PaulBarrett79** [comment]
This has been fixed by Andy - reassigning and moving to awaiting testing

**Comment by KarenPorter** [comment]
I'm pretty sure this is a duplicate?  It has moved on somewhat but there's still an issue in taking forward the processing of a file where you havev previously tries to assign a SMILE column then changed your mind - you get an 'oops' message

**Comment by strets123** [comment]
Refactoring of adding compounds

**Comment by KarenPorter** [comment]
I can no longer upload any file - even one which i have moments before downloaded from that project.  Get message: File cannot be processed, some records or the format is invalid. For excel files, the structure column must be correctly specified and all rows valid.

**Comment by nroam** [comment]
Other than the fact this ought not to be happening, should the error message give more information about what is wrong?  I'm sure you are capturing this internally in the backend, otherwise the exception would not be thrown.

For example:

"Row X is invalid"
"Column Y is not in the expected format"

**Comment by PaulBarrett79** [comment]
This functionality has now been superceded by other work done during this sprint and is now no longer applicable.

Verified on staging/sandbox

**Comment by KarenPorter** [comment]
Agreed - no longer relevant
