### ISSUE TITLE
New behaviour (relatively recently, though I can't say when).

If I upload a file with no structures

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#274]
File in progress issue

New behaviour (relatively recently, though I can't say when).

If I upload a file with no structures to the Playground project it processes fine.  If I upload it, pick a SMILEs column and get the warning message (File cannot be processed...) correctly, I then select No structure for the SMILEs column and I get 'Oops, should not have got here...' message  but the behaviour should be the same as if I never selected a SMILES column.

**Comment by strets123** [comment]
Should now be fixed

**Comment by KarenPorter** [comment]
I've cleared history, ctrl/F5 but still get the same.  I can demo.

**Comment by strets123** [comment]
Now fixed

**Comment by KarenPorter** [comment]
If I process a file with no structure defined - that's OK.  If I select an invalid structure column - I get a warning.  If I then select a valid SMILES column - same warning message.  If I then select no structure - processes, if I then select valid SMILES columns  -warning

**Comment by strets123** [comment]
Need a new version of this issue to cover the possibilities with the new interface

**Comment by strets123** [comment]
Close as irrelevant for now

**Comment by KarenPorter** [comment]
Agreed- close based on new interface experience.
