### ISSUE TITLE
Fix chemdoodle link in bower and update chemdoodle

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#514]
We need to change the license of ng-chem and the overall repository to GPL and put chemdoodle 7 in with the proper download link to avoid breaking license terms

**Comment by aekhendry** [comment]
Andy has recently recomended this be looked at due to a number of bugs in the current chemdoodle window. He estimates that this will take 1.5 days

**Comment by strets123** [comment]
I have completed an integration of my new chemdoodle angular app into chemreg.

The search interface is now powered by this and the code committed to github.

**Comment by strets123** [comment]
https://github.com/strets123/chemdoodle-angular

**Comment by strets123** [comment]
The new chemdoodle implementation is now ready for testing on chembiohub.ox.ac.uk/hubtest. This shoulkd fix all of the explorer issues and the issue of not being able to search for methane.

I have not added anything to do with the query options so should probably disable this.

**Comment by aekhendry** [comment]
Explorer issues still exist

**Comment by strets123** [comment]
Explorer bug should now be fixed

**Comment by aekhendry** [comment]
Im closing this as this issue is now being addressed in issue

**Comment by aekhendry** [comment]
Explorer bug still exists. I'll leave this in testing however as it is also covered in issue 758.

**Comment by strets123** [comment]
Done
